Fixed errno 150 issue
eveningkid/denodb pull request #112
Opened 2020-09-09 03:57 UTC by stillalivx

Hey! I fixed my issue (#106). I just added a conditional to check if primary key field is type integer, in that case, it will add the not nullable property to the field "belongsTo"

2020-09-09 16:46 UTC, eveningkid reviewed
Hi,

Thank you for sending this PR, I really appreciate it!

There's just one question on my side before we merge, thanks.

Keep in touch

2020-09-09 16:46 UTC, eveningkid commented on lib/helpers/fields.ts
> +        table[relationshipPKType](fieldOptions.name).notNullable();
Quick question: how does using `notNullable()` solves it? I thought the issue was between `signed/unsigned int` from #106. Could you please explain it more thoroughly? I am afraid I don't understand..!

2020-09-09 19:06 UTC, stillalivx commented on lib/helpers/fields.ts
> +        table[relationshipPKType](fieldOptions.name).notNullable();
Sorry for the late response, I was checking the issue and I found more problems but I resolved them.
First, you are right, the issue was about the signed/unsigned int. That happens when somebody adds on the primaryKey field the ```autoIncrement``` property.
Also, in the field that contains the foreign key, automatically adds the allow null property, so we have to handle that. The primaryKey doesn't allow the null.
As I said, I already changed the code to fix those issues. Can you request the changes? 
Thanks!

2020-09-13 04:21 UTC, stillalivx commented
Hello! Do you have some comments?

2020-09-22 20:35 UTC, eveningkid requested changes
Hi,

Sorry I only got back to you.

You did a great job, please see my two comments and we'll be good to merge.

It's just a matter of minutes I would say and once it's done I will merge it straight away.

Thank you for your help :)

2020-09-22 20:35 UTC, eveningkid commented on lib/model.ts
> +  /**/
We are a missing a description here of what it does. You can check other methods to see what's the comment style in use :)

2020-09-22 20:35 UTC, eveningkid commented on lib/helpers/fields.ts
> +import {FieldOptions, DataTypes, FieldTypeString, FieldType, FieldProps} from "../data-types.ts";
I don't know why we lost the spaces before and after braces. Can you just put them back please?

2020-09-22 23:36 UTC, stillalivx commented
That's it! The changes are done. :)

2020-09-22 23:38 UTC, eveningkid approved these changes
Great, thanks man! 😁

Have a good day

2020-09-22 23:39 UTC, merged