WIP Feat/migrate to plugin approach
eveningkid/denodb pull request #126
Opened 2020-09-22 20:43 UTC by rluvaton

Migrate to plugin approach #121

2020-09-22 20:51 UTC, rluvaton commented
@eveningkid What should I do with the `SQLTranslator` file?

On one hand, this is per connector, on the other hand, every SQL connector should have almost the exact same SQL translator

The way I see it, there are 2 solutions:
#### 1. Extract to external helper library:
##### Advantages:
1. Extract implementation
2. Avoid code duplication

##### Disadvantages:
1. Too much libraries
2. Another library to maintain

#### 2. Keep the SQL translator but pass custom options
##### Advantages:
1. Fastest solution
2. Avoid code duplication

##### Disadvantages:
1. Not really separation of concerns

2020-09-23 15:13 UTC, eveningkid commented
I think the second option just makes more sense and is closer from what we have at the moment.

You could have one file for each connector's translator, with most of them extending `SQLTranslator`

2020-09-23 15:17 UTC, rluvaton commented
https://github.com/eveningkid/denodb/blob/0adb59871fe1577340aefd8237bf6767bf648e7f/lib/relationships.ts#L36
`Model.name` doesn't exist, did you meant table?

2020-09-23 15:28 UTC, eveningkid commented
@rluvaton `name` is a default property that lives on every class you create:
```js
class A {}

console.log(A.name); // Will print "A"
```

2020-09-23 15:33 UTC, rluvaton commented
> @rluvaton `name` is a default property that lives on every class you create:
> 
> ```js
> class A {}
> 
> console.log(A.name); // Will print "A"
> ```

Cool, didn't know that...
but from SO _AngryHacker_'s comment on this [answer](https://stackoverflow.com/a/36643177/5923666)
> `MyClass.name` won't work well if you are minifying your code. Because it will minify the name of the class. – AngryHacker`

Which is problematic

2020-09-23 23:29 UTC, eveningkid commented
@rluvaton this is not an issue going forward. The code, even minimised, works fine.
Don't find problems where there is none otherwise you'll never be done! :)

2020-09-29 09:01 UTC, rluvaton commented
I'm thinking of creating another Deno package with all the files related for creating a plugin:
- `SqlTranslator`
 - `Translator` interface
and more

so the plugins won't need to import this library which seems odd

2020-10-01 09:43 UTC, U-ways commented
Hello guys, will you fix #115 (Deno 1.4 support) with these changes or should I just submit a PR?

2020-10-01 12:33 UTC, rluvaton commented
> Hello guys, will you fix #115 (Deno 1.4 support) with these changes or should I just submit a PR?

Thanks, it will be best if you submit PR as your issue is more ￼urgent and this PR could take some time.

2020-11-10 23:00 UTC, eveningkid commented
Hi @rluvaton,

Do you think you'll be working on this? I know I went silent.
It seems like a huge project.

Just let me know man, don't put too much on your plate

2020-11-11 01:00 UTC, rluvaton commented
> Hi @rluvaton,
> 
> Do you think you'll be working on this? I know I went silent.
> It seems like a huge project.
> 
> Just let me know man, don't put too much on your plate

Yeah, sorry a lot of stress at work I haven't found any time

> BTW, just pushed, it contains removing any reference to some DB and use interfaces over classes.

2020-11-19 17:58 UTC, rluvaton commented
Hey @eveningkid, glad to say that I think I finished and I'm ready for your review.
Please tell me if there is something else that needed to be done, also please take a close look at the `connector-mod.ts` file to see if there are some exports that I missed.

We also need to fix the documentation to match the current behavior.

I'm really proud of myself that I was able to do it without any major refactoring

2020-12-02 22:28 UTC, eveningkid requested changes
Hi Raz,

I finally took some time to review your work.

I appreciated your approach, it's clean.

You have comments to work from, it shouldn't take too long to make these changes!
There are a few questions also I wish I can have your input on before moving forward.

Also, I left a comment on the transition from the previous way to the new one.
I think that denodb is great because it's simple:

```js
import { Database } from '...';
const database = new Database('mysql', ...);
```

We would now have something like (correct me if I'm wrong):

```js
import { Database } from '...';
import { MySQLConnector } from '...';
const database = new Database(new MySQLConnector({ ... }));
```

I think we should have a way, at least for built-in connectors, to get basic types without additional imports:

```js
import { Database } from '...';
const database = Database.forDialect('mysql', { ... });
// or even keep something similar to the current implementation?
const database = new Database('mysql', ...);
```

Do you think this would be possible? Keeping it open for less common/custom database connectors (maybe MongoDB and others) but really simple for the most common ones (mysql, postgres, sqlite)?

I just think by switching to a different "API", we also need to keep what makes this library simple and great.

Let's discuss more on this, I should be more available this week so keep in touch!

Thank you for your work :)

2020-12-03 12:02 UTC, rluvaton commented
@eveningkid No problem, working on it, thank you for taking the time for reviewing this PR

2020-12-03 12:26 UTC, rluvaton commented on lib/connectors/mongodb/connector.ts
> +      } = await import("./deps.ts");
So should move these dependencies to the main `dep.ts` file?

2020-12-03 13:17 UTC, rluvaton commented on lib/connectors/mysql/connector.ts
> +  _dialect: BuiltInDatabaseDialect = "mysql";
It's not necessary, but to pass to the `SQLTranslator` class you need that the dialect will be the type `BuiltInDatabaseDialect` and if not TypeScript complain about that
> TS2345: Argument of type 'string' is not assignable to parameter of type 'BuiltInDatabaseDialect'.

I can pass string but then I won't be protected by the dialect that can be passed

2020-12-03 13:18 UTC, rluvaton commented on lib/translators/sql-translator.ts
> +  _dialect: BuiltInDatabaseDialect;
The 2nd option looks fine to me, I chosed that

2020-12-03 13:41 UTC, rluvaton commented on lib/connectors/sqlite3/connector.ts
> +      this._dialect as BuiltInDatabaseDialect,
see https://github.com/eveningkid/denodb/pull/126#discussion_r535218398

2020-12-03 14:01 UTC, rluvaton commented on lib/database.ts
> +export type DatabaseOptions =
> Should we support the previous and the new way? With a deprecation warning for the previous way.

I think we should, how do you want to warn them about the deprecation?

> Also, it could be nice to have the following utils for built-in connectors:
> 
> ```js
> const database = Database.forDialect('mysql'); // or .for('mysql')
> // Instead of
> const database = new Database(new MySQLConnector());
> ```
> 
> What do you think?

Agree

2020-12-03 14:50 UTC, rluvaton commented on lib/connectors/postgres/connector.ts
> +  _dialect: BuiltInDatabaseDialect = "postgres";
see https://github.com/eveningkid/denodb/pull/126#discussion_r535218398

2020-12-03 18:14 UTC, rluvaton commented
@eveningkid I changed what you asked and haven't changed the things that I didn't mark as resolve (I'm waiting for your response)

2020-12-04 11:52 UTC, eveningkid commented on lib/connectors/mysql/connector.ts
> +  _dialect: BuiltInDatabaseDialect = "mysql";
Alright, makes sense :)

2020-12-04 11:53 UTC, eveningkid commented on lib/database.ts
> +export type DatabaseOptions =
Agree, and I think the way you did it for warning the users is good

2020-12-04 11:57 UTC, eveningkid commented
Great changes, I really appreciate how fast you worked on this.

I already browsed all your changes but need to work on the mongodb thing first.
Apparently it isn't an unstable dependency anymore. I need to test their new version and then make changes.

I will review this again once that is done.

Keep in touch

2020-12-06 13:19 UTC, rluvaton commented
@eveningkid I merged the recent changes you did for solving the MongoDB dependencies, ready to merge 🚀

2020-12-06 17:57 UTC, eveningkid requested changes
Alright so, I really took some time to think about the last changes because this is a massive shift I believe.

You really did a good job and my only hope is that these comments can help you reflect on your code. I don't write all of these comments to say you did a bad job, that's quite the opposite.

I am really glad you are contributing this project and I wish my comments can also help you see your code from a different perspective.

Please consider everything I wrote, nothing is major anymore. Only minor changes really.

Have a nice evening, I will review your changes when sent!

PS: how do you find all this time to work on this? Are you a student? :)

2020-12-06 17:57 UTC, eveningkid commented on README.md
> +}));
I think if things were split in two steps, it might help to understand the *method*/way-of-thinking better:
```js
const connection = new PostgresConnector({
  host: '...',
  username: 'user',
  password: 'password',
  database: 'airlines',
});

const db = new Database(connection);
```

2020-12-06 17:57 UTC, eveningkid commented on README.md
> +  }));
Same as above here. I think before wrapping things together it is good to remember that a user has never seen denodb before and therefore needs to quickly grasp the way things are done

2020-12-06 17:57 UTC, eveningkid commented on README.md
> +
Again, we should think long term: migrations might happen again later.

```markdown
## Migrate from previous versions
- `v1.0.21`: [Migrate to connectors](MIGRATION.md)
```

Also, just thinking about it now: let's create a `docs` folder and move `/MIGRATION.md` to `docs/version-migrations/connectors.md`. I am thinking of adding all the documentation pages on this repo later so everyone can contribute (...just me at the moment).

Then just change the link to:

```markdown
- `v1.0.21`: [Migrate to connectors](docs/version-migrations/connectors.md)
```

2020-12-06 17:57 UTC, eveningkid commented on deps.ts
>  export { MongoClient as MongoDBClient } from "https://deno.land/x/mongo@v0.20.0/mod.ts";
I kind of felt this way when reading the comments:

```js
// Name
const name = ...;
```

I think it's important to minimise noise with comments that aren't really bringing additional information. Each dependency name contains the database type in it (mongo, sqlite, deno-postgres...), and it is not too important to mention which deps are for connectors

2020-12-06 17:57 UTC, eveningkid commented on lib/connectors/factory.ts
> +import { BuiltInDatabaseDialect } from "../database.ts";
Just wondering (not too sure if I'm right): shouldn't it be `import type { BuiltInDatabaseDialect } ...`?

I remember having errors being raised when importing a type without `import type`. Let me know

2020-12-06 17:57 UTC, eveningkid commented on lib/connectors/mongodb-connector.ts
> +
We have an extra line here before translator

2020-12-06 17:57 UTC, eveningkid commented on lib/connectors/mongodb-connector.ts
> +  _translator: Translator;
In other connectors you put `_translator` with other properties (not with `_dialect`).

I think it's better to have `_translator` grouped with the others below as you did in the other files

2020-12-06 17:57 UTC, eveningkid commented on lib/database.ts
> +          "[denodb]: If you want to migrate to the current behavior, visit https://github.com/eveningkid/denodb/blob/master/MIGRATION.md#dialect-to-connector for help",
After changing that file location, remember to change the file link here :)

2020-12-06 17:57 UTC, eveningkid commented on lib/database.ts
> +      // @ts-ignore
Just wondering what was the warning for this?

2020-12-06 17:57 UTC, eveningkid commented on lib/translators/sql-translator.ts
> +export type SupportedSqlDatabaseDialect =
We used `SQL` everywhere else so this should be consistent:
`SupportedSqlDatabaseDialect` -> `SupportedSQLDatabaseDialect`

This also needs to be changed anywhere `SupportedSqlDatabaseDialect` was in use

2020-12-06 17:57 UTC, eveningkid commented on lib/translators/sql-translator.ts
> +// These are the supported Database dialect types for the SQLQueryBuilder that we use
Could you please add a link to where you found that information? It is just in case someday someone needs to find where that came from, and just need to click on that link.

You can also keep the message short:
```js
// Supported database dialect types for the SQLQueryBuilder in use:
// <add_link>
```

2020-12-06 17:57 UTC, eveningkid commented on lib/connectors/sqlite3-connector.ts
> +  SupportedSqlDatabaseDialect,
I think we also need a `import type { ... }` here instead. This is also on the other SQL-compatible connectors

2020-12-06 17:57 UTC, eveningkid commented on mod.ts
> +export type { Connector } from "./lib/connectors/connector.ts";
Since we have connector-related exports here, why not having all of them in `mod.ts`?

I just feel that the smaller the better. If we can have `mod.ts` only instead of `mod.ts` **and** `connector-mod.ts`.

If your intention was to minimise the imports in case a new package is only using the connector imports from denodb (to create a new connector I believe), these imports (in `mod.ts`) will still be loaded at some point when using that new connector anyway.

I could be wrong but I am not sure this would really improve the performance if that was your idea

2020-12-06 17:57 UTC, eveningkid commented on connector-mod.ts
> +export {
Please see my comment on `mod.ts` about this file which I believe its contents should be transferred to `mod.ts`

2020-12-06 17:57 UTC, eveningkid commented on MIGRATION.md
> +import { DataTypes, Database, Model } from 'https://deno.land/x/denodb/mod.ts';
Keep the imports minimal, we only use `Database` below

2020-12-06 17:57 UTC, eveningkid commented on MIGRATION.md
> +import { DataTypes, Database, Model, PostgresConnector } from 'https://deno.land/x/denodb/mod.ts';
Same here, only `Database` and `PostgresConnector`. Might be good to have the same pattern I suggested in another comment:

```js
const connection = new PostgresConnector(...);
const db = new Database(connection);
```

For all the other examples below in this file, please change the imports and use that pattern when necessary to clarify code samples

2020-12-06 18:05 UTC, rluvaton commented
> Alright so, I really took some time to think about the last changes because this is a massive shift I believe.
> 
> You really did a good job and my only hope is that these comments can help you reflect on your code. I don't write all of these comments to say you did a bad job, that's quite the opposite.
> 
> I am really glad you are contributing this project and I wish my comments can also help you see your code from a different perspective.
> 
> Please consider everything I wrote, nothing is major anymore. Only minor changes really.
> 
> Have a nice evening, I will review your changes when sent!
Of course, every review it's something to learn from

> PS: how do you find all this time to work on this? Are you a student? :)

I'm a student but also I work full time. I just love to contribute to open source projects 🚀

2020-12-06 18:22 UTC, rluvaton commented on lib/connectors/factory.ts
> +import { BuiltInDatabaseDialect } from "../database.ts";
You are absolutely right, probably missed that

2020-12-06 18:24 UTC, rluvaton commented on lib/database.ts
> +      // @ts-ignore
he complains about 
> TS2339: Property 'dialect' does not exist on type 'Connector | ConnectorDatabaseOptions | { dialect: BuiltInDatabaseDialect; debug?: boolean | undefined; disableDialectUsageDeprecationWarning?: boolean | undefined; }'.   Property 'dialect' does not exist on type 'Connector'.

2020-12-06 18:28 UTC, rluvaton commented on lib/database.ts
> +      // @ts-ignore
I cast it instead

2020-12-06 18:48 UTC, rluvaton commented on lib/translators/sql-translator.ts
> +export type SupportedSqlDatabaseDialect =
@eveningkid  I understand but the `SupportedSqlDatabaseDialect` are the supported databases for the `SQLTranslator`. to create only one type `SupportedSQLDatabaseDialect` we need to implement those

2020-12-06 18:54 UTC, rluvaton commented on mod.ts
> +export type { Connector } from "./lib/connectors/connector.ts";
I wasn't trying to improve the performance, I did this to help developers that want to create a connector to understand which modules are needed to create one.

2020-12-06 19:18 UTC, rluvaton commented on lib/translators/sql-translator.ts
> +// These are the supported Database dialect types for the SQLQueryBuilder that we use
Unfortunately, there is no central place for this (I opened an issue https://github.com/knex/documentation/issues/299 about this).
Which reminds me - maybe we should write in the README the DBs that we support out of the box and their corresponding dialect names.

In each dialect implementation, there is a `dialect` property.

2020-12-06 20:41 UTC, rluvaton commented
@eveningkid I answered some of your review comments, apart from that I finished, when you'll answer my responses I'll update accordingly.

2020-12-27 00:55 UTC, rluvaton commented
@eveningkid any update?

2020-12-27 18:32 UTC, eveningkid commented
Hi Raz, sorry for the long wait!

I am working a lot on a mobile app at the same time and planned to release it soon.
It is also around Christmas time and I have less time for managing open-source projects.

Don't worry, it is always in the back of my mind.

I wish I had more time.
Be assured it will be done, thank you for your patience!

2021-01-02 13:54 UTC, eveningkid commented
Just a quick update Raz, I will be looking at this later today

2021-01-02 17:10 UTC, eveningkid approved these changes
All good, I will finally merge and update the online website shortly!

It's been months, so thank you really for your long-time dedication to this project.

It is the first time I see someone trying to help that much on a project I started, so thank you!

I hope you had a nice time around this time of the year, and the best for the one to come :)

2021-01-02 17:11 UTC, merged

2021-01-02 17:12 UTC, rluvaton commented
> All good, I will finally merge and update the online website shortly!
> 
> 
> 
> It's been months, so thank you really for your long-time dedication to this project.
> 
> 
> 
> It is the first time I see someone trying to help that much on a project I started, so thank you!
> 
> 
> 
> I hope you had a nice time around this time of the year, and the best for the one to come :)

Glad to help! 😀

2021-01-02 17:38 UTC, eveningkid commented
If you want to take a look, I just published the new docs with your approach: http://eveningkid.com/denodb-docs/docs/guides/connect-database (it's also in the guides for each database type)!

2021-01-02 17:40 UTC, rluvaton commented
> If you want to take a look, I just published the new docs with your approach: http://eveningkid.com/denodb-docs/docs/guides/connect-database (it's also in the guides for each database type)!

You forgot to mention that they can create custom connectors.

2021-01-02 17:49 UTC, eveningkid commented
You are right.

I just pushed all the documentation pages to a different repository so it's easy for you to contribute there if you want.

https://github.com/eveningkid/denodb-documentation

It's all in markdown so it's more convenient than on the previous one I think!

2021-01-02 18:05 UTC, rluvaton commented
@eveningkid Also, this version contains breaking changes, I think you should publish it under _major_ version number 2, to help users identify there is a breaking changes