Let's fix some bugs !
eveningkid/denodb pull request #157
Opened 2020-12-02 10:47 UTC by techtastet

- I added some tests to check if everything is okay before merge
- I fixed the crash when an update in MySQL is executed (updatedAt field was the reason)
- And I fixed an oversight in the types file :)

Hope all this will be useful in the future ;)

2020-12-02 15:59 UTC, eveningkid requested changes
Hi Thomas,

Thanks for all your efforts :)

Almost there, I left a few comments.
Shouldn't take too long to make these changes (it's just to make it all blend perfectly).

We can merge after these changes are done.

Keep in touch!

2020-12-02 15:59 UTC, eveningkid commented on tests/connection.ts
> +const ConnectionMySQL = (): Database => {
- The naming could be confusing as it implies this is a class, although when used you don't have to instantiate it. `getMySQLConnection()` would be more descriptive.
- Would be great if the options could be overwritten —if we ever need to do so:
```js
const getMySQLConnection = (options? = {}): Database => {
  // ...later merges options with { database: ... }
};
```

2020-12-02 15:59 UTC, eveningkid commented on tests/units/MySQL/connection.test.ts
> +  const connection = ConnectionMySQL();
Every time in use, the name/import should be replaced then! 😄

2020-12-02 15:59 UTC, eveningkid commented on tests/units/MySQL/models.test.ts
> +  const connection = ConnectionMySQL();
Here too.

2020-12-02 15:59 UTC, eveningkid commented on tests/units/MySQL/models.test.ts
> +  delete result.updatedAt;
Would the following still be necessary if we set `Flight.timestamps = false`?

I wonder actually. From what I remember, these fields are only added when `timestamps = true`.

2020-12-02 15:59 UTC, eveningkid commented on tests/units/Relationships/Foreinkey.test.ts
> +  static table = "foreinkeyowners";
`foreiGnkeyowners`, there are missing `g`s in that file (in the filename as well).

Just need to replace these

2020-12-02 15:59 UTC, eveningkid commented on tests/units/Relationships/Foreinkey.test.ts
> +  static table = "foreinkeybusinesses";
Same here (I just pin it so you wouldn't have to resend another commit later haha)

2020-12-02 15:59 UTC, eveningkid commented on tests/units/Relationships/Foreinkey.test.ts
> +Deno.test("MySQL - Forein Key test", async function () {
Same

2020-12-02 15:59 UTC, eveningkid commented on tests/units/Relationships/Foreinkey.test.ts
> +  const connection = ConnectionMySQL();
Remember to change the name here as well

2020-12-02 15:59 UTC, eveningkid commented on tests/units/Relationships/Foreinkey.test.ts
> +  delete OwnerTest.updatedAt;
Same question as in the other file. Is it needed if `timestamps = false`?

2020-12-02 15:59 UTC, eveningkid commented on tests/units/queries/update.test.ts
> +  const connection = ConnectionMySQL();
Same

2020-12-02 15:59 UTC, eveningkid commented on tests/units/queries/update.test.ts
> +  delete article.updatedAt;
...same! 😄

2020-12-02 15:59 UTC, eveningkid commented on tests/units/Relationships/Foreinkey.test.ts
> +import { DataTypes, Model, Relationships } from "../../../mod.ts";
Just wondering what's the filename coming from. There are capital letters in this one but not in the query test suite.

I think it is common to keep these lowercased as you did with the queries :)

2020-12-04 11:00 UTC, techtastet commented
done @eveningkid :)

2020-12-04 11:25 UTC, eveningkid approved these changes
Hi Thomas,

There are still a few typos so I'll make a commit after merging.

Thank you for your work, I will merge now :)

2020-12-04 11:25 UTC, merged