fix/cant-drop-linked-tables-138
eveningkid/denodb pull request #174
Opened 2021-01-02 23:41 UTC by rluvaton

2021-01-02 23:58 UTC, rluvaton commented on deps.ts
> +export { Client as PostgresClient } from "https://raw.githubusercontent.com/denodrivers/postgres/master/mod.ts";
`deno-postgres/deno-postgres`  just redirecting to `denodrivers/postgres` so I update it

2021-01-03 00:03 UTC, rluvaton commented
@eveningkid Can you please help me why the tests are failing? 🤔

2021-01-15 21:53 UTC, eveningkid commented
Hi Raz,

I checked the tests logs and [this unit test](https://github.com/eveningkid/denodb/blob/master/tests/units/queries/update.test.ts#L20) failed.

I believe the issue comes from what `topologicalSortModelSchema` returns.
You can run the test locally with your branch changes and it should be easier to find the error with some logging:

```ts
console.log(models);
this._models = topologicalSortModelSchema(models);
console.log(this._models); // See if two logs differ
```

I think the problem lies [in these lines](https://github.com/eveningkid/denodb/pull/174/files#diff-a26658091de6e970f22159c3a89f2f48cedf73467268b989633f654929865665R20-R22). Static properties are not copied and so `Model.table` gets lost in the process.

You could look into this and I am sure the tests will then pass.
I am sure you will find the error with some logging and trying this unit test on your end!

Thank you for your work, and sorry for the long wait.

Keep in touch

2021-01-16 18:17 UTC, rluvaton commented
> Hi Raz,
> 
> I checked the tests logs and [this unit test](https://github.com/eveningkid/denodb/blob/master/tests/units/queries/update.test.ts#L20) failed.
> 
> I believe the issue comes from what `topologicalSortModelSchema` returns.
> You can run the test locally with your branch changes and it should be easier to find the error with some logging:
> 
> ```ts
> console.log(models);
> this._models = topologicalSortModelSchema(models);
> console.log(this._models); // See if two logs differ
> ```
> 
> I think the problem lies [in these lines](https://github.com/eveningkid/denodb/pull/174/files#diff-a26658091de6e970f22159c3a89f2f48cedf73467268b989633f654929865665R20-R22). Static properties are not copied and so `Model.table` gets lost in the process.
> 
> You could look into this and I am sure the tests will then pass.
> I am sure you will find the error with some logging and trying this unit test on your end!
> 
> Thank you for your work, and sorry for the long wait.
> 
> Keep in touch

Thanks, haven't had much time lately to debug why it was failing but thanks

2021-01-17 21:23 UTC, eveningkid requested changes
Hi Raz,

Just had a look at your code.

I know you might be annoyed by the comments since all of them are related to code-readability!

I really like things to be simple, so if we could keep a few lines off.

It's safe to merge after that!

2021-01-17 21:23 UTC, eveningkid commented on lib/database.ts
> +      // We want to reverse the order because we want the one that have no dependencies first to be dropped (at the opposite order of insertion).
I think the last comment is the most important and please change it to:

```js
// Reverse the order so the models without dependencies are dropped first
```

2021-01-17 21:23 UTC, eveningkid commented on lib/database.ts
> +    this._models = topologicalSortModelSchema(models);
I think this could be one-lined without a comment, if you change the function name a little:

```js
this._models = sortModelsByDependencies(models);
```

Then it says what it does (so no need for a comment) and if someone wonders how it's sorted, they can jump to the function to read more

2021-01-17 21:23 UTC, eveningkid commented on lib/helpers/sort-model-schema.ts
> + * @param models
No description?

And `@param` is defined in the function signature

2021-01-17 21:23 UTC, eveningkid commented on lib/helpers/sort-model-schema.ts
> +      tableNameToModel[model.table] = model;
If you look at [`Model.table`](https://github.com/eveningkid/denodb/blob/master/lib/model.ts#L69), you'll see that if we have two models with `.table` undefined, this code will break.

Maybe one idea: add a `.getName()` which returns the class' name. Then this would become:

```js
tableNameToModel[model.getName()] = model;
```

2021-01-17 21:23 UTC, eveningkid commented on deps.ts
> +// We use CDN cause it's an npm package (with no dependencies or Node.js builtins).
I think it's okay to remove this comment. It is quite common at the moment since Deno is new...right?

2021-01-17 21:23 UTC, eveningkid commented on lib/database.ts
> +  // The order is important.
```js
// Inter-dependent models come first, and the ones without dependencies come last
```

2021-01-17 21:26 UTC, rluvaton commented
> I know you might be annoyed by the comments since all of them are related to code-readability!

Code readability is super important, I totally understand you, I'm very strict in my team when I do code review.


> I really like things to be simple, so if we could keep a few lines off.

Off course

2021-01-17 22:35 UTC, rluvaton commented on lib/helpers/sort-model-schema.ts
> +      tableNameToModel[model.table] = model;
You are right that this code will break on `undefined` (and even on the same string), **but** table name must **never** have the same name, am I wrong? In any database (that I'm aware of) there are no 2 tables with the same name, therefore I don't think it's the right place to handle models with the same table name.

What do you think? 🤔

2021-01-17 22:43 UTC, eveningkid commented on lib/helpers/sort-model-schema.ts
> +      tableNameToModel[model.table] = model;
You are right! Maybe this could be inside `getName()`?

```js
getName() {
  if (!this.table) {
    throw new Error(`Every model requires a table name. Define one using \`static table = "my_table"\`.`);
  }

  return this.table;
}
```

And whenever we call `.table` we could replace it with `.getName()` instead?

If you have another idea this is open for discussion!

2021-01-17 22:47 UTC, rluvaton commented on lib/helpers/sort-model-schema.ts
> +      tableNameToModel[model.table] = model;
I think that's a good idea as long as this is the current process,
Plus, I think the name should be a getter function like this:
```ts
get name(): string {
  if (!this.table) {
    throw new Error(`Every model requires a table name. Define one using \`static table = "my_table"\`.`);
  }

  return this.table;
}
```

2021-01-17 23:02 UTC, rluvaton commented on lib/helpers/sort-model-schema.ts
> +      tableNameToModel[model.table] = model;
On second thought, I don't think that every `getName` call would throw an error, the only place that should get the models is the `link` function in the `Database.ts` file, this is where I think the validation should happen (although users _could_ change the table name on runtime it's very unlikely)

2021-06-19 18:48 UTC, rluvaton commented
Hey @eveningkid, is this PR still needed?

2021-06-19 22:10 UTC, eveningkid commented
Oh no, sorry I totally missed you sent your changes!

Not sure. Could you try and see with the original issue using the latest version?

If it's still relevant I'll review your code again.

Thanks again for your help, it truly means a lot to me :)

2023-01-02 22:41 UTC, closed without merging