Add charset support for mysql
eveningkid/denodb pull request #218
Opened 2021-04-06 00:54 UTC by Aiko-Suzuki

2021-04-06 10:33 UTC, eveningkid requested changes
Hey Aiko,

This is great, I wasn't aware of this option so let's make it available to everybody :)

I know it's annoying, but if you could just remove the extra spaces first, then I'll be able to merge this.

Thank you!

2021-04-06 10:33 UTC, eveningkid commented on lib/connectors/mysql-connector.ts
> +  charset? : string;
`charset?: string;`, there's an extra space here

2021-04-06 10:33 UTC, eveningkid commented on lib/connectors/mysql-connector.ts
> +      charset : this._options.charset ?? "utf8",
And here again: `charset: this._options...`

2021-04-06 11:21 UTC, Aiko-Suzuki commented
there you go should be fine now

2021-04-06 11:25 UTC, eveningkid approved these changes
All good, thanks!

Have a great day :)

2021-04-06 11:25 UTC, merged

2021-06-18 15:53 UTC, aronmalkine commented
Shouldn't this be the non-broken 'utf8mb4' value instead here?