Edit: SQLite query response. (#223)
eveningkid/denodb pull request #236
Opened 2021-04-19 20:22 UTC by stillalivx

After thinking about what might be the best way to return information, I think keeping things simple and returning essential data allows users to be clear in their code, doesn't it? I just made some changes inside the _query method and created some tests to check if it works as expected with any method. :) Tell me if you want some changes.

2021-04-19 23:11 UTC, eveningkid requested changes
Ahh, it is so cool when things can be simple!

Thank you so much for your work, this is the best solution.
It took a long discussion but it was worth it :)

We can merge after you remove that log

2021-04-20 00:44 UTC, stillalivx commented on tests/units/queries/sqlite/response.test.ts
> +  console.log(createResponse);
Oh, I can't believe it.

2021-04-20 23:36 UTC, eveningkid approved these changes

2021-04-20 23:37 UTC, eveningkid commented
Great, all good now :)

Thank you for helping, really.

Have a good day!

2021-04-20 23:37 UTC, merged