convert mongo _id string to objectId
eveningkid/denodb pull request #240
Opened 2021-04-22 00:51 UTC by borsemayur2

2021-04-25 10:34 UTC, eveningkid requested changes
Alright Mayur, thank you for giving this a try really :)

You've done well, it's just about codebase consistency and readability at this point.

We can soon merge with these few changes, keep it up!

2021-04-25 10:34 UTC, eveningkid commented on deps.ts
> +export { Bson } from "https://deno.land/x/mongo@v0.22.0/mod.ts";
It would be better if Bson was imported from the same other mongo import on line 18

2021-04-25 10:34 UTC, eveningkid commented on lib/connectors/mongodb-connector.ts
> +import { Bson } from "../../deps.ts";
Same thing here, both imports on line 1 and 6 can be put together :)

2021-04-25 10:34 UTC, eveningkid commented on lib/data-types.ts
> +export type FieldValue = number | string | boolean | Date | null | object;
Isn't it possible to be more precise than `object` here? Like the `Bson` type or something.
And please keep `null` as the very last case, thanks

2021-04-25 10:34 UTC, eveningkid commented on lib/connectors/mongodb-connector.ts
> +
We have an extra line here to remove

2021-04-25 10:34 UTC, eveningkid commented on lib/connectors/mongodb-connector.ts
> +      }
Always ask yourself: what does someone who know nothing about the codebase would understand?

What does `i` stand for?

It's better if the name reflects what it contains, it could be `let whereClause` for example!

Btw, I wonder if it has to be `let` here since it's an object we're changing. Since you're not doing `i = something_new;`, I think it's safe to use `const` because it's just updating an attribute. Give it a try and see if that works

2021-04-26 01:37 UTC, borsemayur2 commented on lib/data-types.ts
> +export type FieldValue = number | string | boolean | Date | null | object;
I found [`ObjectId`](https://deno.land/x/mongo@v0.22.0/bson/bson.d.ts#L969) type but do not know how to import it exactly. Is the following way correct to import it?

```
import { Bson } from "../deps.ts";

type ObjectId = Bson.ObjectId;

export type FieldValue = number | string | boolean | Date | ObjectId | null ;
```
![image](https://user-images.githubusercontent.com/47341981/116017545-86488100-a65d-11eb-8b7d-43c734254714.png)

2021-04-26 08:53 UTC, eveningkid approved these changes
All good, thank you Mayur!

Let's merge this

2021-04-26 08:53 UTC, merged