Added: Logger option in MySQLConnection
eveningkid/denodb pull request #245
Opened 2021-04-25 20:27 UTC by stillalivx

Hey, @eveningkid! I was wondering if is possible to add this option to MySQL connection. With it, users could control the log messages that MySQL driver shows at the console. If you want more information, denodrivers has [this](https://github.com/denodrivers/mysql#logging) little section. 
I use it when I want to run some tests and the log data makes a caos with the test's messages

This is how it works:
```typescript
const connector = new MySQLConnector({
  ... // essential data connection
  logger: { // Logger options (it's not only enable)
    enable: false
  }
});
```

2021-04-25 21:50 UTC, eveningkid requested changes
No problem, totally legit :)

Just have a look at the comments and we can merge.

Thank you!

2021-04-25 21:50 UTC, eveningkid commented on deps.ts
> +  log as MySQLLogs,
This one is exported but never used

2021-04-25 21:50 UTC, eveningkid commented on deps.ts
> +  configLogger as MySQLConfigLogger,
I think it's misleading to use PascalCase here, it makes me think it's a class and not a function.

Maybe name it `configMySQLLogger` instead?

2021-04-25 21:50 UTC, eveningkid commented on lib/connectors/mysql-connector.ts
> +  LoggerConfig,
Shouldn't this one be `import type { LoggerConfig } ...`? Not sure

2021-04-26 00:01 UTC, stillalivx commented
Okay, I think it's ready.

2021-04-26 08:50 UTC, eveningkid commented
All good, let's merge :)

Thank you!

2021-04-26 08:51 UTC, eveningkid approved these changes

2021-04-26 08:51 UTC, merged