Added: _wrapValuesWithDefaults
eveningkid/denodb pull request #248
Opened 2021-04-26 22:36 UTC by stillalivx

Hi, @eveningkid. I already implement the function that you mention in issue #198. I tested and it works as expected!

2021-04-27 20:50 UTC, eveningkid requested changes
Small changes to make and we're good to go :)

Thank you, as always

2021-04-27 20:50 UTC, eveningkid commented on lib/model.ts
>      }
I think we don't need this here as it's already happening inside `_wrapValuesWithDefaults`.

You could just remove all this and then do:

```js
const createdInstance = await model.create({});
```

But then it would be misleading because...how come we create an instance without passing any value?

A better approach I feel would be to keep the `this.hasOwnProperty(field)` part inside `save()` (just like what you have already) but remove it from `_wrapValuesWithDefaults`. That method would then only wrap defaults around a given `Values` and not bring class properties into it

2021-04-27 20:50 UTC, eveningkid commented on lib/model.ts
> +        values[field] = (this as any)[field];
That's the part I'm refering to in my other comment. You could get rid of this and just keep `if (this.defaults...)`

2021-04-27 20:50 UTC, eveningkid commented on lib/model.ts
> +  /* Wraps values with defaults */
We're missing a "." here :')

2021-04-28 01:52 UTC, stillalivx commented on lib/model.ts
>      }
Yeah, I though the same, but there is a problem:

When you create an intance of `Model` to use it with method `.save()`, the values don't pass as expected because `.create()` is static type. So, inside `create()`,  `this` doesn't reffer to the instance of `Model` but the class instead.

That took me hours to realize... 😣

2021-04-28 20:54 UTC, eveningkid commented on lib/model.ts
>      }
I'm afraid I don't understand the issue. My suggestion was to have this:

```js
private static _wrapValuesWithDefaults(values: Values): Values {
    for (const field of Object.keys(this.fields)) {
      if (values.hasOwnProperty(field)) {
        continue;
      }

      // if (this.hasOwnProperty(field)) {
      //   values[field] = (this as any)[field];
      // } else
      
      if (this.defaults.hasOwnProperty(field)) {
        const defaultValue = this.defaults[field];

        if (typeof defaultValue === "function") {
          values[field] = defaultValue();
        } else {
          values[field] = defaultValue;
        }
      }
    }

    return values;
  }
```

Maybe you could send me code examples to explain the issue, we'll understand each other better!

2021-04-29 00:35 UTC, stillalivx commented on lib/model.ts
>      }
Okay, okay, I get it.

Just let me explain the problem to do something like this:
```js
const createdInstance = await model.create({});
```
If we have this code:
```js
class Costumer extends Model {
  ...
  
  static defaults  = {
    date: () => new Date()
  }; 
}

const costumer1 = new Costumer();

costumer1.name = "Costumer Name";
costumer1.company = "Company Name";

costumer1.save();
```
So suppose that we don't have [this loop](https://github.com/eveningkid/denodb/pull/248/files#diff-a04536623242819a50c31f164d2c7edca3773a3c462a48f57f1806096c8328c9R972) to save the properties of that instance. If `_wrapValuesWithDefaults` tries to get that properties from the instance (`costumer1`) of the model (`Costumer`) we will receibe something like:
```js
{ name: "Costumer Name", company: "Company Name", date: "xx/xx/xxxx xx:xx:xx" } // expected result
{ name: null, company: null, date: "xx/xx/xxxx xx:xx:xx" } // Result
```
This because inside `_wrapValuesWithDefaults`, the object `this` refers to `Costumer` instead of `costumer1`. This is because `_wrapValuesWithDefaults` is static type.

2021-04-29 09:27 UTC, eveningkid commented on lib/model.ts
>      }
Ohk man, I think we just misunderstood each other :D

Using `.create({})` was just my first thought but I didn't see this would break indeed.

Thanks for explaining it!

2021-04-29 09:27 UTC, eveningkid approved these changes

2021-04-29 09:28 UTC, eveningkid commented
All good now!

This project is really moving forward thanks to your work, I'm very happy you're here.

Let's merge this :)

2021-04-29 09:28 UTC, merged