Postgres connect with url string
eveningkid/denodb pull request #254
Opened 2021-04-30 03:03 UTC by borsemayur2

2021-04-30 03:06 UTC, borsemayur2 commented
Related to #253

2021-05-01 10:37 UTC, eveningkid requested changes
Hey Mayur,

Thank you for contributing to the project :)

I left you a note, I'll wait for your reply.

Have a great day

2021-05-01 10:37 UTC, eveningkid commented on lib/connectors/postgres-connector.ts
> +}
This notation really confused me. Shouldn't it be:

```ts
interface PostgresOptionsWithConfig extends ConnectorOptions {
  database: string;
  host: string;
  username: string;
  password: string;
  port?: number;
}

interface PostgresOptionsWithURI extends ConnectorOptions {
  uri: string;
}

export type PostgresOptions = PostgresOptionsWithConfig | PostgresOptionsWithURI;
```

2021-05-01 10:53 UTC, borsemayur2 commented on lib/connectors/postgres-connector.ts
> +}
This was indeed my initial approach. But TypeScript throws error so I used `never`.
![image](https://user-images.githubusercontent.com/47341981/116780281-46d4c700-aa99-11eb-8dcb-1840e5c5a786.png)
![image](https://user-images.githubusercontent.com/47341981/116780302-77b4fc00-aa99-11eb-8163-88f20b545021.png)

2021-05-01 11:11 UTC, eveningkid commented on lib/connectors/postgres-connector.ts
> +}
Alright, the reason is `hasOwnProperty` doesn't [work as a typescript type guard](https://stackoverflow.com/a/59200046).

So you can keep your original thought and replace the check with:

```js
if ("uri" in options) {
  // shouldn't raise an error
  this._client = new PostgresClient(options.uri);
}
```

That's great to know! I would have done the same mistake :D

2021-05-01 12:17 UTC, borsemayur2 commented on lib/connectors/postgres-connector.ts
> +}
done

2021-05-01 20:50 UTC, eveningkid approved these changes

2021-05-01 20:51 UTC, eveningkid approved these changes
All good, Mayur :)

Thanks, will merge now and make a new release!

Have a great day

2021-05-01 20:52 UTC, merged