add: orWhere & andWhere methods
eveningkid/denodb pull request #281
Opened 2021-07-18 05:42 UTC by stillalivx

I added the orWhere and andWhere methods. I read your comment about a cool API to add these clauses like "automatically", but I thing that this is a good temportal solution. The query or & and are very usefull and denodb has to include them (also to close issue #197)

Ah, in addition, I left a little issue (#280) about a weird behavior, I hope you can check it out!

2021-07-30 00:11 UTC, eveningkid requested changes
Hey,

It's been a while and to be honest with you, I opened this PR a few days ago and completely forgot to send you my comments!

So here there are. I think there's not so much to change, it's more about refactoring your code and we should be good.

This is a really good feature, thank you for your work!

Keep in touch

2021-07-30 00:11 UTC, eveningkid commented on lib/query-builder.ts
> +export type WhereMethod = "none" | "and" | "or";
I don't think that `none` should be represented as a string here but `undefined` instead (and come last). This should also be changed in other files (I've seen it in `model.ts`, not sure about others)

2021-07-30 00:11 UTC, eveningkid commented on lib/query-builder.ts
> +    const whereClause: WhereClause = {
Just wondering: would it trigger an error if there was no `: WhereClause` here?

2021-07-30 00:11 UTC, eveningkid commented on lib/translators/sql-translator.ts
> +          case "none":
So this should become the default case instead

2021-07-30 00:11 UTC, eveningkid commented on lib/query-builder.ts
> +export type WhereMethod = "none" | "and" | "or";
Oh and btw, could you add an extra line between `WhereMethod` and the previous `QueryType`?

2021-08-11 23:10 UTC, stillalivx commented on lib/model.ts
> +  }
Hi! I'm having problems traying to implement this part. In the methods where, andWhere & orWhere there are a conditions to verify the arguments. That is a problem 'cause is necessary in every method. I tried to pass all the arguments with a spread operator to `_where`:
```js
private static _where(...) {
  if (...) {
    ...
    this._currentQuery.where(...);
  } else {
    ...
    this._currentQuery.where(...);
  }
}

static andWhere(...) {
  const args = Array.from(arguments) // If I pass arguments directly, it throws an error (arguments is not an iterable)
  return this._where("and", ...args); // Throws error "A spread argument must either have a tuple type or be passed to a rest parameter"
}
```
But that throws a syntax error. I can't see how to proceed.

2021-12-21 06:50 UTC, closed without merging