Update dex and mongodb deps
eveningkid/denodb pull request #307
Opened 2021-11-19 21:38 UTC by Zhomart

NOTE: don't merge, still testing

2021-12-07 15:40 UTC, eveningkid requested changes
First of all, thank you for your work Zhomart, it is highly appreciated!

For some reason, I missed the email and then got many notifications from linked issues. I am happy your work will help everybody else!

You'll find a few comments/questions below. If I can get your feedback on these, that would be helpful to move this forward.

Have a great day, talk soon :)

2021-12-07 15:40 UTC, eveningkid commented on deps.ts
> +// NOTE: these changes fixes #303.
We don't need this line I think, it's fine to use your fork without a note :)

2021-12-07 15:40 UTC, eveningkid commented on lib/connectors/sqlite3-connector.ts
>      const results = subqueries.map(async (subquery, index) => {
Do we need this ignore line if we remove the `async` on the next line?

Because I see `async` but no `await` in the map callback. Maybe `async` can be removed and also the ignore comment.

What do you think? Am I missing something?

2021-12-07 15:40 UTC, eveningkid commented on lib/connectors/sqlite3-connector.ts
> +            result.count = row[columnName] as FieldValue;
Just wondering why we use `row[columnName]` and not `value` like in the other conditions?

2021-12-07 15:40 UTC, eveningkid commented on deps.ts
> +export type { Database as MongoDBDatabase } from "https://deno.land/x/mongo@v0.28.0/src/database.ts";
Just wondering: is `0.28.0` not using unstable API anymore? (I guess you checked before, that's just out of curiosity)

2021-12-11 02:46 UTC, Zhomart commented on deps.ts
> +// NOTE: these changes fixes #303.
I'll put a better note, my fork may stay in old version forever )

2021-12-11 02:53 UTC, Zhomart commented on lib/connectors/sqlite3-connector.ts
>      const results = subqueries.map(async (subquery, index) => {
dang, apparently we can use Promise.resolve() below, thanks

2021-12-11 02:59 UTC, Zhomart commented on lib/connectors/sqlite3-connector.ts
> +            result.count = row[columnName] as FieldValue;
looks like I forgot to use value there. Also added count tests

2021-12-11 03:08 UTC, Zhomart commented on deps.ts
> +export type { Database as MongoDBDatabase } from "https://deno.land/x/mongo@v0.28.0/src/database.ts";
It didn't ask any unstable flag when testing locally. I believe it was fixed.

You can take a look at CI/CD logs

2021-12-11 03:10 UTC, Zhomart commented on deps.ts
> +// NOTE: these changes fixes #303.
Update the hash again, now the dependent `dex` is using the latest `deno std library`. 
PTAL https://github.com/Zhomart/dex/blob/930253915093e1e08d48ec0409b4aee800d8bd0c/lib-dyn/deps.ts

2021-12-11 03:13 UTC, Zhomart commented
Thanks eveningkid for reviewing!

2021-12-12 09:54 UTC, erfanium commented on deps.ts
> +export type { Database as MongoDBDatabase } from "https://deno.land/x/mongo@v0.28.0/src/database.ts";
No it doesn't use any unstable API

2021-12-13 16:13 UTC, eveningkid requested changes
Thank you again for making all the changes :)

Please find below the last tiny tweak and we're good to merge!

2021-12-13 16:13 UTC, eveningkid commented on tests/units/queries/sqlite/response.test.ts
> +  assertEquals(articleCound, 2, "Return article count")
I'm going to be annoying, but that's the last thing before we merge! :D

1) add `;` at the end of lines 87 and 89
2) change `articleCound` (with a D) to `articleCount` on l.87 and l.89 (I hate when this happens too!)

2021-12-13 16:26 UTC, Zhomart commented on tests/units/queries/sqlite/response.test.ts
> +  assertEquals(articleCound, 2, "Return article count")
Done!

2021-12-13 16:50 UTC, eveningkid commented
Cool, I'll merge and create a new release!

Have a great day Zhomart :)

2021-12-13 16:50 UTC, eveningkid approved these changes

2021-12-13 16:51 UTC, merged

2021-12-13 18:20 UTC, l3onh4rd commented
Thank you for your great work!!! For me this fixed my problem ;) It even works with deno version 1.16.4. Hopefully it won't break with tomorrow releasing version 1.17.0...